In [1]:
import numpy as np

In [2]:
#Arange
numbers_array=np.arange(10)
print("Array of numbers:",numbers_array)

Array of numbers: [0 1 2 3 4 5 6 7 8 9]


In [3]:
numbers_array_start_stop=np.arange(start=3,stop=10)
print(numbers_array_start_stop)

[3 4 5 6 7 8 9]


In [4]:
numbers_array_with_step=np.arange(start=2,stop=12,step=2)
print(numbers_array_with_step)

[ 2  4  6  8 10]


In [5]:
#np.linspace
#Contineous
seq_array=np.linspace(start=4,stop=6,num=10)
print(seq_array)

[4.         4.22222222 4.44444444 4.66666667 4.88888889 5.11111111
 5.33333333 5.55555556 5.77777778 6.        ]


In [6]:
seq_array_exc_end=np.linspace(start=4,stop=6,num=10,endpoint=False)
print(seq_array_exc_end)

[4.  4.2 4.4 4.6 4.8 5.  5.2 5.4 5.6 5.8]


In [7]:
seq_array_exc_end_ret=np.linspace(start=4,stop=6,num=10,endpoint=False,retstep=True)
print(seq_array_exc_end_ret)
seq_array_exc_end_ret[0]
seq_array_exc_end_ret[1]

(array([4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8]), 0.2)


0.2

In [8]:
seq_2d_array=np.linspace(start=[2,3,5],stop=[4,6,7],num=5)
print(seq_2d_array)

[[2.   3.   5.  ]
 [2.5  3.75 5.5 ]
 [3.   4.5  6.  ]
 [3.5  5.25 6.5 ]
 [4.   6.   7.  ]]


In [9]:
seq_2d_array_axis1=np.linspace(start=[2,3,5],stop=[4,6,7],num=5,axis=1)
print(seq_2d_array_axis1)


[[2.   2.5  3.   3.5  4.  ]
 [3.   3.75 4.5  5.25 6.  ]
 [5.   5.5  6.   6.5  7.  ]]


In [10]:
#Geospace
geo_space=np.geomspace(start=1,stop=128,num=8)
print(geo_space)

[  1.   2.   4.   8.  16.  32.  64. 128.]


In [11]:
log_space=np.logspace(start=2,stop=10,num=5,base=2)
print(log_space)

[   4.   16.   64.  256. 1024.]


In [12]:
#Arrays
array_1d=np.array(['A','B','C'])
array_1d
                

array(['A', 'B', 'C'], dtype='<U1')

In [13]:
array_2d=np.array([['A','B','C'],['D','E','F']])
array_2d

array([['A', 'B', 'C'],
       ['D', 'E', 'F']], dtype='<U1')

In [17]:
array_3d=np.array([[['A','B','C'],['D','E','F'],['G','H','I']],[['A','B','C'],['D','E','F'],['G','H','I']],
                   [['A','B','C'],['D','E','F'],['G','H','I']]])
array_3d


array([[['A', 'B', 'C'],
        ['D', 'E', 'F'],
        ['G', 'H', 'I']],

       [['A', 'B', 'C'],
        ['D', 'E', 'F'],
        ['G', 'H', 'I']],

       [['A', 'B', 'C'],
        ['D', 'E', 'F'],
        ['G', 'H', 'I']]], dtype='<U1')

In [18]:
array_3d.ndim
array_3d.shape

(3, 3, 3)

In [19]:
array_3d.strides

(36, 12, 4)

In [21]:
ones_3d=np.ones([2,3,4],dtype=np.int32)
ones_3d

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [22]:
zeros_3d=np.zeros([2,3,3,2],dtype=np.int32)
zeros_3d

array([[[[0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0]]],


       [[[0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0]]]])